### ISSUE TITLE
[duplication] When multiple smelting is enabled

### ISSUE THREAD

**Issue by kreezxil** [Commoble/jumbo-furnace#3]
I have multiple smelting enabled. And for the most part this works as intended. But when clay balls are put in, a stack of 16 will produce 9 stacks of 64.

My config:
```toml
["Cooking Settings"]
	#Maximum recipes the Jumbo Furnace is able to process simultaneously
	#Range: > 1
	max_simultaneous_recipes = 9
	#Cook Time
	#Range: > 1
	cooktime = 100
```

https://youtu.be/atH_Mjc_dIU

Version: 1.15.2-1.0.0.2
Forge: 1.15.2-31.2.41
